name: Build and Test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - CC: clang
            CFLAGS: "-O2 -g3 -Wall -Werror -Wno-unknown-pragmas -Wno-implicit-const-int-float-conversion -Wno-unused-function"
          - CC: gcc
            CFLAGS: "-O2 -g3 -Wall -Werror -Wno-unknown-pragmas"
        php:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
    name: "Build and Test (PHP ${{ matrix.php }}, CC: ${{ matrix.compiler.CC }})"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0

      - name: Set up PHP
        uses: shivammathur/setup-php@72ae4ccbe57f82bbe08411e84e2130bd4ba1c10f # 2.25.5
        with:
          php-version: ${{ matrix.php }}
          tools: none

      - name: Build
        run: phpize && ./configure CFLAGS="${{ matrix.compiler.CFLAGS }}" CC=${{ matrix.compiler.CC }} --silent && make --silent

      - name: Run tests
        run: make test
        env:
          NO_INTERACTION: "1"
          REPORT_EXIT_STATUS: "1"
