name: Build and Test
on:
  push:
    branches:
      - "**"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  ci:
    if: ${{ !contains(github.event.head_commit.message, '[ci skip]') || github.event_name == 'workflow_dispatch' }}
    strategy:
      fail-fast: false
      matrix:
        compiler:
          - CC: clang
            CFLAGS: "-O2 -g3 -Wall -Werror -Wno-unknown-pragmas -Wno-implicit-const-int-float-conversion -Wno-unused-function"
          - CC: gcc
            CFLAGS: "-O2 -g3 -Wall -Werror -Wno-unknown-pragmas"
        php:
          - '7.1'
          - '7.2'
          - '7.3'
          - '7.4'
          - '8.0'
          - '8.1'
          - '8.2'
    name: "Build and Test (PHP ${{ matrix.php }}, CC: ${{ matrix.compiler.CC }})"
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # tag=v3.0.2

      - name: Set up PHP
        uses: shivammathur/setup-php@cdb037c2a47e89a90eb317c7376c32a4cf92ddcc # tag=2.20.0
        with:
          php-version: ${{ matrix.php }}
          tools: none

      - name: Build
        run: phpize && ./configure CFLAGS="${{ matrix.compiler.CFLAGS }}" CC=${{ matrix.compiler.CC }} --silent && make --silent

      - name: Run tests
        run: make test
        env:
          NO_INTERACTION: "1"
          REPORT_EXIT_STATUS: "1"
